name: Publish Docker Image
on: push

Jobs:
  push_docker_images_to_registery:
    name: push Docker image to registry
    runs-on: ubuntu-latest 

    steps:
      - name: check out Repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
